'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.8794
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Cabañas.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property BotonAgregar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonAgregar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonAgregar2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonAgregar2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonCerrar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonCerrar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonCerrar2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonCerrar2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonEliminar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonEliminar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonEliminar2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonEliminar2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonModificar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonModificar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonModificar2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonModificar2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property can_stock_photo_csp42993829() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("can-stock-photo_csp42993829", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dark_Blue_620x387_z9Tu6fR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dark-Blue-620x387_z9Tu6fR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fondo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FondoMaderaClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondoMaderaClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FondoMaderaClaro2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondoMaderaClaro2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FondoMaderaClaro3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondoMaderaClaro3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FondoMaderaPanel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondoMaderaPanel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icono_calendario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icono_calendario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IconoCabania() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoCabania", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IconoCalendario2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoCalendario2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IconoHuesped() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoHuesped", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IconoHuespedSombra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoHuespedSombra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property orig_372503() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orig_372503", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property th1_372503() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("th1_372503", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property thumb_COLOURBOX24169832() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thumb_COLOURBOX24169832", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
